export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import Providers from "./ChackraProvider";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
