import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import Providers from "./ChackraProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <meta
          http-equiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
